# Generated by Django 2.2.7 on 2019-12-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191203_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
