# Generated by Django 2.2.7 on 2019-12-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='nam',
        ),
    ]
