# Generated by Django 2.2.7 on 2019-12-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191203_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='nam',
        ),
    ]
