# Generated by Django 2.2.7 on 2019-12-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
