# Generated by Django 2.2.7 on 2019-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField()),
                ('em', models.EmailField(max_length=254)),
                ('pas', models.TextField()),
                ('rad', models.TextField()),
            ],
        ),
    ]
