# Generated by Django 2.2.7 on 2019-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='con',
            field=models.TextField(null=True),
        ),
    ]
