# Generated by Django 2.2.7 on 2019-12-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_user_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='con',
        ),
    ]
