# Generated by Django 2.2.7 on 2019-12-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_user_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_description', models.CharField(max_length=50)),
                ('job_skills', models.CharField(max_length=50)),
                ('job_career_level', models.CharField(max_length=50)),
                ('job_positions', models.IntegerField(max_length=50)),
                ('job_country', models.CharField(max_length=50)),
                ('job_degree_level', models.CharField(max_length=50)),
                ('job_min_experience', models.CharField(max_length=20)),
                ('job_max_experience', models.CharField(max_length=20)),
                ('job_min_sallery', models.IntegerField(max_length=50)),
                ('job_max_sallery', models.IntegerField(max_length=50)),
                ('job_prefrence', models.CharField(max_length=20)),
            ],
        ),
    ]
