# Generated by Django 3.0 on 2019-12-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_subject', models.CharField(max_length=30)),
                ('feedback_disc', models.CharField(max_length=100)),
            ],
        ),
    ]
