# Generated by Django 3.0.2 on 2020-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='intoresume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_resume_name', models.CharField(max_length=30)),
                ('d_resume_fname', models.CharField(max_length=30)),
                ('d_resume_cnic', models.CharField(max_length=30)),
                ('d_resume_gender', models.CharField(max_length=10)),
                ('d_resume_region', models.CharField(max_length=20)),
                ('d_resume_degreelevel', models.CharField(max_length=20)),
                ('d_resume_subdegreelevel', models.CharField(max_length=20)),
                ('d_resume_skills', models.CharField(max_length=50)),
                ('d_resume_experience', models.CharField(max_length=20)),
            ],
        ),
    ]
