# Generated by Django 3.0.2 on 2020-01-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_intoresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_career_level_periority',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_degree_level_periority',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_experience_periority',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_prefrence_periority',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_skills_periority',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
