# Generated by Django 3.0.2 on 2020-01-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20200128_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_career_level_periority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_degree_level_periority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_experience_periority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_prefrence_periority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skills_periority',
            field=models.CharField(max_length=50),
        ),
    ]
