# Generated by Django 3.0.2 on 2020-01-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20200128_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_title',
            field=models.IntegerField(default=1000, max_length=5),
            preserve_default=False,
        ),
    ]
