# Generated by Django 3.0.2 on 2020-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_intoresume_d_resume_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_career_level',
            field=models.CharField(default=685, max_length=20),
            preserve_default=False,
        ),
    ]
