# Generated by Django 3.0.2 on 2020-01-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20200128_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_max_experience',
        ),
    ]
