# Generated by Django 3.0.2 on 2020-01-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_remove_job_job_max_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intoresume',
            name='d_resume_counter',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
