# Generated by Django 2.2.9 on 2020-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_remove_feedback_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intoresume',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
