# Generated by Django 3.0.2 on 2020-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intoresume',
            name='d_resume_title',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='recommended',
            name='d_resume_title',
            field=models.CharField(max_length=5),
        ),
    ]
