# Generated by Django 3.0.2 on 2020-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20200214_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='call_for_interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_resume_title', models.CharField(max_length=50)),
                ('d_resume_name', models.CharField(max_length=30)),
                ('d_resume_fname', models.CharField(max_length=30)),
                ('d_resume_cnic', models.CharField(max_length=30)),
                ('d_resume_gender', models.CharField(max_length=10)),
                ('d_resume_region', models.CharField(max_length=20)),
                ('d_resume_career_level', models.CharField(max_length=50)),
                ('d_resume_degreelevel', models.CharField(max_length=20)),
                ('d_resume_subdegreelevel', models.CharField(max_length=20)),
                ('d_resume_skills', models.CharField(max_length=50)),
                ('d_resume_experience', models.CharField(max_length=20)),
                ('d_resume_counter', models.IntegerField(default=0, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
