# Generated by Django 2.2.9 on 2020-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_call_for_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_for_interview',
            name='d_resume_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intoresume',
            name='d_resume_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_career_level_periority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_degree_level_periority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_experience_periority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_max_sallery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_min_sallery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_positions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_prefrence_periority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skills_periority',
            field=models.IntegerField(),
        ),
    ]
