# Generated by Django 2.2.9 on 2020-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20200217_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='d_resume_counter',
            field=models.IntegerField(default=0),
        ),
    ]
