# Generated by Django 2.2.9 on 2020-02-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
