# Generated by Django 2.2.9 on 2020-02-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
