# Generated by Django 2.2.9 on 2020-02-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_type_con'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
