# Generated by Django 2.2.9 on 2020-02-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='disc',
            field=models.TextField(max_length=1000),
        ),
    ]
