# Generated by Django 2.2.9 on 2020-02-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20200223_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, default='No Response Yet', max_length=500, null=True),
        ),
    ]
