# Generated by Django 2.2.9 on 2020-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_feedback_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
