# Generated by Django 2.2.9 on 2020-02-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_feedback_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='call_for_interview',
        ),
        migrations.DeleteModel(
            name='intoresume',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='recommended',
        ),
    ]
