# Generated by Django 2.2.9 on 2020-02-23 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0046_auto_20200223_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_resume_title', models.CharField(max_length=50)),
                ('d_resume_name', models.CharField(max_length=30)),
                ('d_resume_fname', models.CharField(max_length=30)),
                ('d_resume_cnic', models.CharField(max_length=30)),
                ('d_resume_gender', models.CharField(max_length=10)),
                ('d_resume_region', models.CharField(max_length=20)),
                ('d_resume_career_level', models.CharField(max_length=50)),
                ('d_resume_degreelevel', models.CharField(max_length=20)),
                ('d_resume_subdegreelevel', models.CharField(max_length=20)),
                ('d_resume_skills', models.CharField(max_length=50)),
                ('d_resume_experience', models.CharField(max_length=20)),
                ('d_resume_counter', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('job_description', models.CharField(max_length=50)),
                ('job_skills', models.CharField(max_length=50)),
                ('job_skills_periority', models.IntegerField()),
                ('job_career_level', models.CharField(max_length=50)),
                ('job_career_level_periority', models.IntegerField()),
                ('job_positions', models.IntegerField()),
                ('job_country', models.CharField(max_length=50)),
                ('job_degree_level', models.CharField(max_length=50)),
                ('job_degree_level_periority', models.IntegerField()),
                ('job_min_experience', models.CharField(max_length=20)),
                ('job_experience_periority', models.IntegerField()),
                ('job_min_sallery', models.IntegerField()),
                ('job_max_sallery', models.IntegerField()),
                ('job_prefrence', models.CharField(max_length=20)),
                ('job_prefrence_periority', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='intoresume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_resume_title', models.CharField(max_length=50)),
                ('d_resume_name', models.CharField(max_length=30)),
                ('d_resume_fname', models.CharField(max_length=30)),
                ('d_resume_cnic', models.CharField(max_length=30)),
                ('d_resume_gender', models.CharField(max_length=10)),
                ('d_resume_region', models.CharField(max_length=20)),
                ('d_resume_career_level', models.CharField(max_length=50)),
                ('d_resume_degreelevel', models.CharField(max_length=20)),
                ('d_resume_subdegreelevel', models.CharField(max_length=20)),
                ('d_resume_skills', models.CharField(max_length=50)),
                ('d_resume_experience', models.CharField(max_length=20)),
                ('d_resume_counter', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='call_for_interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_resume_title', models.CharField(max_length=50)),
                ('d_resume_name', models.CharField(max_length=30)),
                ('d_resume_fname', models.CharField(max_length=30)),
                ('d_resume_cnic', models.CharField(max_length=30)),
                ('d_resume_gender', models.CharField(max_length=10)),
                ('d_resume_region', models.CharField(max_length=20)),
                ('d_resume_career_level', models.CharField(max_length=50)),
                ('d_resume_degreelevel', models.CharField(max_length=20)),
                ('d_resume_subdegreelevel', models.CharField(max_length=20)),
                ('d_resume_skills', models.CharField(max_length=50)),
                ('d_resume_experience', models.CharField(max_length=20)),
                ('d_resume_counter', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
