# Generated by Django 3.0.3 on 2020-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='intoresume',
            name='d_resume_contact',
            field=models.CharField(default='03165009006', max_length=30),
        ),
    ]
