# Generated by Django 3.0.3 on 2020-02-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20200224_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call_for_interview',
            old_name='d_resume_fname',
            new_name='d_resume_email',
        ),
        migrations.RenameField(
            model_name='recommended',
            old_name='d_resume_fname',
            new_name='d_resume_email',
        ),
    ]
