# Generated by Django 3.0.3 on 2020-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_recommended_calforinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommended',
            name='forjob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
