# Generated by Django 2.2 on 2020-02-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_recommended_forjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='call_for_interview',
        ),
    ]
