# Generated by Django 2.2 on 2020-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_delete_call_for_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intoresume',
            name='d_resume_skills',
            field=models.CharField(max_length=1000),
        ),
    ]
