# Generated by Django 3.0.4 on 2020-04-08 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0058_auto_20200409_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('S', 'Seller'), ('B', 'Buyer')], max_length=1)),
                ('emcon', models.CharField(max_length=15)),
                ('confirmm', models.BooleanField(default=False)),
                ('pconfirm', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.TextField()),
                ('Lname', models.TextField()),
                ('seller_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_title', models.TextField()),
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_description', models.TextField()),
                ('prod_price', models.FloatField(default=0.0)),
                ('prod_category', models.CharField(default='House', max_length=15)),
                ('prod_files', models.FileField(upload_to='media/products')),
                ('prod_loc', models.TextField()),
                ('prod_status', models.TextField(default='Inactive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('c_name', models.TextField(primary_key=True, serialize=False)),
                ('c_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('phone', models.TextField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='b_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Fname', models.TextField()),
                ('user_Lname', models.TextField()),
                ('user_password', models.TextField()),
                ('user_email', models.EmailField(default='None', max_length=254)),
                ('user_level', models.CharField(default='Level-0', max_length=10)),
                ('user_type', models.CharField(default='Generic', max_length=10)),
                ('user_city', models.CharField(default='N/A', max_length=20)),
                ('user_address', models.TextField()),
                ('user_postal_code', models.CharField(default='00000', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
