# Generated by Django 3.0.4 on 2020-04-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_b_user_contact_product_seller_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='con',
            field=models.BooleanField(default=False),
        ),
    ]
