# Generated by Django 3.0.3 on 2020-04-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_type_con'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seller',
        ),
    ]
