# Generated by Django 3.0.3 on 2020-04-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
