# Generated by Django 3.0.3 on 2020-04-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_seller_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='b_User',
        ),
    ]
