# Generated by Django 3.0.3 on 2020-04-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='profile_pic',
        ),
    ]
