# Generated by Django 3.0.4 on 2020-04-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_remove_buyer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_email',
        ),
    ]
