# Generated by Django 3.0.4 on 2020-04-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_remove_seller_seller_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
