# Generated by Django 3.0.4 on 2020-04-12 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0068_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.TextField()),
                ('prod_description', models.TextField()),
                ('prod_price', models.FloatField(default=0.0)),
                ('prod_category', models.CharField(default='House', max_length=15)),
                ('prod_files', models.FileField(upload_to='media/products')),
                ('prod_loc', models.TextField()),
                ('prod_status', models.TextField(default='Inactive')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
