# Generated by Django 3.0.4 on 2020-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_product_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auction_status',
            field=models.CharField(choices=[('F', 'Finished'), ('NF', 'Not Finished')], default='NF', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_status',
            field=models.CharField(choices=[('S', 'Started'), ('NS', 'Not Started')], default='NS', max_length=2),
        ),
    ]
