# Generated by Django 3.0.4 on 2020-04-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_auto_20200413_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tframe',
            field=models.IntegerField(default=24),
        ),
    ]
