# Generated by Django 3.0.4 on 2020-04-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_product_tframe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seller',
        ),
    ]
