# Generated by Django 3.0.4 on 2020-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0077_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
