# Generated by Django 3.0.4 on 2020-04-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_seller_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
