# Generated by Django 3.0.4 on 2020-04-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0080_auto_20200413_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
