# Generated by Django 3.0.4 on 2020-04-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0088_remove_comment_buy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
