# Generated by Django 3.0.4 on 2020-04-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0090_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
