# Generated by Django 3.0.4 on 2020-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0092_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='com',
            field=models.IntegerField(default=0),
        ),
    ]
