# Generated by Django 3.0.4 on 2020-04-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0093_buyer_com'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
