# Generated by Django 3.0.4 on 2020-04-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0095_auto_20200415_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
