# Generated by Django 3.0.4 on 2020-04-14 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0096_auto_20200415_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(blank=True, max_length=20)),
                ('CNIC', models.CharField(max_length=20, unique=True)),
                ('phone_no', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('city', models.CharField(default='N/A', max_length=15)),
                ('address', models.CharField(max_length=75)),
                ('postal_code', models.CharField(blank=True, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
