# Generated by Django 3.0.4 on 2020-04-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0097_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
