# Generated by Django 3.0.4 on 2020-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0101_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='endtime',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='starttime',
            field=models.CharField(default='', max_length=50),
        ),
    ]
