# Generated by Django 3.0.4 on 2020-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0102_auto_20200415_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
