# Generated by Django 3.0.4 on 2020-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0103_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nofbidder',
            field=models.IntegerField(default=0),
        ),
    ]
