# Generated by Django 3.0.4 on 2020-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0104_product_nofbidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='lbids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer',
            name='sbids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tbids',
            field=models.IntegerField(default=0),
        ),
    ]
