# Generated by Django 3.0.4 on 2020-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0105_auto_20200416_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='CNIC',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='CNIC',
            field=models.CharField(max_length=20),
        ),
    ]
