# Generated by Django 3.0.4 on 2020-04-18 01:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0106_auto_20200416_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bid',
            new_name='Bidding',
        ),
    ]
