# Generated by Django 3.0.4 on 2020-04-18 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0109_auto_20200418_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidwons',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
