# Generated by Django 2.2.5 on 2020-06-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0111_auto_20200418_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, upload_to='media/ContactUS'),
        ),
    ]
