# Generated by Django 3.1 on 2020-08-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0112_auto_20200627_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('B', 'Buyer'), ('G', 'Guest')], max_length=1),
        ),
    ]
