# Generated by Django 3.1 on 2020-08-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0113_auto_20200819_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.TextField()),
                ('c_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('phone', models.TextField()),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='media/ContactUS')),
            ],
        ),
    ]
