# Generated by Django 3.1 on 2020-08-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0114_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': ['prod_title']},
        ),
    ]
