# Generated by Django 3.1 on 2020-08-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0116_auto_20200823_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': ['created_date']},
        ),
    ]
