# Generated by Django 3.1 on 2020-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0119_auto_20200909_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='CNIC',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='CNIC',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
